# Generated by Django 4.0.2 on 2022-04-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_apptitude_video_interview_corner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptitude_video',
            name='companyName',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
