# Generated by Django 4.0.2 on 2022-04-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_apptitude_video_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptitude_video',
            name='companyName',
            field=models.CharField(max_length=20),
        ),
    ]
