# Generated by Django 4.0.2 on 2022-04-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CS_IT_Course',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=10)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
