# Generated by Django 4.0.2 on 2022-04-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_trending_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs_it_course',
            name='courseName',
            field=models.TextField(),
        ),
    ]
