# Generated by Django 4.0.2 on 2022-04-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0004_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('field', models.CharField(max_length=25)),
                ('platform', models.CharField(max_length=10)),
                ('query', models.TextField()),
            ],
        ),
    ]
