# Generated by Django 4.0.2 on 2022-04-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactUs',
        ),
    ]
