# Generated by Django 4.0.2 on 2022-04-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0006_delete_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('prnNo', models.CharField(max_length=25)),
                ('departmentName', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=20)),
                ('cgpa', models.CharField(max_length=10)),
                ('phno', models.CharField(max_length=15)),
                ('bdate', models.DateField()),
            ],
        ),
    ]
