# Generated by Django 4.0.2 on 2022-04-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='companydescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='perks',
            field=models.TextField(blank=True),
        ),
    ]
